import type { Section } from './TermsPrimitives';

export const SECTIONS: Section[] = [
  { id: 'acceptance',  label: 'Acceptance of Terms',               anchor: 'acceptance'  },
  { id: 'atlas-terms', label: 'The ATLAS Terms of Use',            anchor: 'atlas-terms' },
  { id: 'definitions', label: 'A. Definitions',                    anchor: 'definitions' },
  { id: 'account',     label: 'B. Account Terms',                  anchor: 'account'     },
  { id: 'platform',    label: 'C. Platform Use',                   anchor: 'platform'    },
  { id: 'tenant',      label: 'D. Tenant Obligations',             anchor: 'tenant'      },
  { id: 'landlord',    label: 'E. Landlord/Manager Obligations',   anchor: 'landlord'    },
  { id: 'payments',    label: 'F. Payments and Billings',          anchor: 'payments'    },
  { id: 'privacy',     label: 'G. Privacy and Data',               anchor: 'privacy'     },
  { id: 'prohibited',  label: 'H. Prohibited Conduct',             anchor: 'prohibited'  },
  { id: 'disclaimers', label: 'I. Disclaimers & Limitation',       anchor: 'disclaimers' },
  { id: 'termination', label: 'J. Termination',                    anchor: 'termination' },
  { id: 'governing',   label: 'K. Governing Law',                  anchor: 'governing'   },
  { id: 'contact',     label: 'Contact Us',                        anchor: 'contact'     },
];

export interface DefinitionEntry {
  term: string;
  definition: string;
}

export const DEFINITIONS: DefinitionEntry[] = [
  {
    term: 'ATLAS',
    definition:
      'The ATLAS website and all related digital services operated by the ATLAS team.',
  },
  {
    term: 'User',
    definition:
      'Any individual who creates an account or accesses the platform, including tenants, students, landlords, and housing managers.',
  },
  {
    term: 'Tenant / Student',
    definition:
      'A user who browses listings, applies for units, and manages their lease through the platform.',
  },
  {
    term: 'Landlord / Manager',
    definition:
      'A user who lists dormitory units, manages tenancies, and processes billing through the platform.',
  },
  {
    term: 'Listing',
    definition:
      'A dormitory room or unit posted on the platform by a landlord or housing manager for tenant applications.',
  },
  {
    term: 'Content',
    definition:
      'All text, images, data, and other material submitted to or generated by the platform by users or ATLAS.',
  },
];